### ISSUE TITLE
Erro 403 ambiente de produção

### ISSUE THREAD

**Issue by ebragav** [marcelobelli/PyNFSe#33]
O ambiente piloto funcionou 100%, porém o ambiente de produção esta dando erro 403 de permissão negada, já fiz todos os procedimentos solicitados no manual da prefeitura de Curitiba.

A única coisa que estou na dúvida é a respeito da cadeia de certificação - servidor produção.

Tenho que passar a cadeia na conexão? Se sim, como faço isso?

**Comment by marcelobelli** [comment]
403 é a prefeitura respondendo com acesso proibido. Fiz um teste aqui pra garantir e deu boa a emissão.

Perguntas:
1. Qual ambiente está rodando a lib?
2. Vc consegue acessar o site de produção para emissão de nota com o certificado?

Roda o código abaixo (com os devidos ajustes):
```
from pynfse.base.certificate import get_certificate

cert_ca, cert_file, key, key_file = get_certificate(<CAMINHO DO CERTIFICADO>, <SENHA DO CERTIFICADO>)

for line in cert_file: 
    print(line)
```
3. O resultado é algo assim?
```
-----BEGIN CERTIFICATE-----
blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah
blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah
blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah
blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah
blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah
blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah
blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah
blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah
blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah
-----END CERTIFICATE-----
```
Repara que dentro do certificado existe mais de um certificado. Isso é a cadeia de certificação do teu certificado. Se só aparecer um `BEGIN...END CERTIFICATE` é pq o teu certificado não é o original, aquele que vc pega com a certificadora. Ele provavelmente é uma cópia que foi exportado sem a cadeia de certificação, daí vai dar ruim mesmo na hora de autenticar no soap da prefeitura.

**Comment by ebragav** [comment]
Realizei os testes solicitados e o certificado da Certisign que estava utilizando não estava com a cadeia de certificação.

Pesquisando no site da Certisign, encontrei o manual no link abaixo, portanto executei o passo a passo e funcionou.

**Exportação do Certificado A1:**
https://www.certisign.com.br/duvidas-suporte/manual/manual-exportacao-certificado-a1-win-internet-explorer
